### ISSUE TITLE
File open in thread pool

### ISSUE THREAD

**Issue by FHRNet** [nginx/nginx#417]
Hi,

would it be possible to provide updated patches for aio_open / moving file opens to thread pools please?
https://mailman.nginx.org/pipermail/nginx-devel/2021-August/014194.html

### Describe the feature you'd like to add to nginx

Offload file open() operations for static file serving and cache to thread pools

### Describe the problem this feature solves

Utilizing `aio_open on;` introduced by the patchset linked above significantly improves http latency under specific high load scenarios - servers handling a large amount of files under significant I/O stress. However, the logic is not compatible with newer nginx versions.

### Additional context

There seems to be a conflict with this commit https://github.com/nginx/nginx/commit/b794465178ecf48f13b37e4397145b05fd3fe6df leading to segfaults when the patches are manually applied against a 1.27.1 codebase and cache is enabled.
```
thread_pool testpool threads=100;
http {
  proxy_cache_valid 200 206 1m;
  proxy_cache_path /tmp/cache levels=1:2 keys_zone=cache:1m;
  proxy_cache_min_uses 1;

  server {
    aio threads=testpool;
    aio_write on;
    aio_open on;

    location /foo {
        proxy_cache cache;
        proxy_pass http://127.0.0.1:12345/index.html;
    }
...
```

backtrace:
```
Thread 1 "nginx" received signal SIGSEGV, Segmentation fault.
0x00005555556b2642 in ngx_event_add_timer (timer=60000, ev=0x555555d073c0) at src/event/ngx_event_timer.h:56
56	    key = ngx_current_msec + timer;
(gdb)
(gdb) bt
#0  0x00005555556b2642 in ngx_event_add_timer (timer=60000, ev=0x555555d073c0) at src/event/ngx_event_timer.h:56
#1  ngx_http_cache_thread_handler (task=0x555555d073a0, file=<optimized out>) at src/http/ngx_http_file_cache.c:883
#2  0x000055555564cf12 in ngx_thread_open (file=0x7fffffffd810, name=0x555555d07368 "/tmp/cache/c/52/9ef0ad7904e995d8fa9b1edaee53952c", mode=mode@entry=2048, create=create@entry=0, access=access@entry=0, pool=pool@entry=0x555555d055a0)
    at src/os/unix/ngx_files.c:158
#3  0x0000555555642793 in ngx_open_uncached_file (name=name@entry=0x555555d07088, of=of@entry=0x555555d05a30, pool=0x555555d055a0, pool@entry=0xf802ad5f902cca00) at src/core/ngx_open_file_cache.c:506
#4  0x0000555555643c7c in ngx_open_cached_file (cache=<optimized out>, name=name@entry=0x555555d07088, of=of@entry=0x555555d05a30, pool=0xf802ad5f902cca00) at src/core/ngx_open_file_cache.c:160
#5  0x00005555556b388a in ngx_http_file_cache_aio_open (c=0x555555d07080, r=0x555555d055f0) at src/http/ngx_http_file_cache.c:667
#6  ngx_http_file_cache_read (r=0x555555d055f0, c=0x555555d07080) at src/http/ngx_http_file_cache.c:500
#7  0x00005555556ad295 in ngx_http_upstream_cache (u=0x555555d06a30, r=0x555555d055f0) at src/http/ngx_http_upstream.c:908
.....
(gdb) f 0
#0  0x00005555556b2642 in ngx_event_add_timer (timer=60000, ev=0x555555d073c0) at src/event/ngx_event_timer.h:56
56	    key = ngx_current_msec + timer;
(gdb) l
51	ngx_event_add_timer(ngx_event_t *ev, ngx_msec_t timer)
52	{
53	    ngx_msec_t      key;
54	    ngx_msec_int_t  diff;
55
56	    key = ngx_current_msec + timer;
57
58	    if (ev->timer_set) {
59	        /*
60	         * Use a previous timer value if difference between it and a new
...
```

I can confirm that commenting out the `ngx_add_timer(&task->event, 60000);` call in `ngx_http_cache_thread_handler(...)` fixes the crashing, though I had very limited success in figuring out why that actually is so far; I don't see an obvious connection between the patches here.

**Comment by u5surf** [comment]
@FHRNet 
Hi, I'm instresting in your suggestion. Because I’m the reporter that issue which had resolved by your referred commit!
For I have already retired the organization which encountered this issue, I might have not reproduced cache status stacking which occurred by the combination worker shutdown and the special settings now. Simply, the long standing issue for me, I appreciate for your suggestion if it resolves the cache status stacking issue even though the commit reverted and applied your patch.
Please let me know if there is anything I can help you.


https://trac.nginx.org/nginx/ticket/2162#comment:3
